-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 07:03:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SOMSAdb
-- -----------------------------------------------------
-- Database for the Marist Capping 2020 project.

-- -----------------------------------------------------
-- Schema SOMSAdb
--
-- Database for the Marist Capping 2020 project.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SOMSAdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `SOMSAdb` ;

-- -----------------------------------------------------
-- Table `SOMSAdb`.`Account`
-- Edited 11/5/2020
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOMSAdb`.`Account` (
  `Account_ID` INT NOT NULL AUTO_INCREMENT,
  `Password` VARCHAR(60) NOT NULL,
  `Email` VARCHAR(60) NOT NULL,
  `Username` VARCHAR(60) NOT NULL,
  `Is_Admin` BOOLEAN NOT NULL DEFAULT 0,
  PRIMARY KEY (`Account_ID`),
  UNIQUE INDEX `Account_ID_UNIQUE` (`Account_ID` ASC) VISIBLE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `SOMSAdb`.`Topic`
   --Updated 11/5/2020
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOMSAdb`.`Topic` (
  `Topic_ID` INT NOT NULL AUTO_INCREMENT,
  `Topic_Name` VARCHAR(120) NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Topic_ID`),
  UNIQUE INDEX `Topic_ID_UNIQUE` (`Topic_ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SOMSAdb`.`Sentiment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SOMSAdb`.`Sentiment` (
  `Sentiment_ID` INT NOT NULL AUTO_INCREMENT,
  `Confidence_Interval` INT NOT NULL,
  PRIMARY KEY (`Sentiment_ID`),
  UNIQUE INDEX `idSentiment_UNIQUE` (`Sentiment_ID` ASC) VISIBLE)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;