FROM node
WORKDIR /usr/src/server
COPY  package*.json ./
RUN npm install
COPY . .
EXPOSE 5000

# wait for db to start up
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait
CMD /wait && dev start